# Generated by Django 6.0.2 on 2026-03-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companydb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lives',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
