# Generated by Django 6.0.2 on 2026-03-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('no_of_courses', models.IntegerField()),
            ],
        ),
    ]
